In [1]:
import cooler
import os
import numpy as np
import pandas as pd

def compute_number_of_copies(cool, chromosomes, contig):
    """Estimates the number of copies of a sequence in the genome from Hi-C data (cool file). 
    The following formula is applied:
        # copies = Cov(contig)/Median(Cov(chromosome))
    with Cov(x) = Reads(x)/Size(x) for any sequence x.
    """
    sequences = np.concatenate([chromosomes, np.array([contig])])
    matrix = cool.matrix(balance = False)
    reads = {seq: 0 for seq in sequences}
    # Estimating each sequence number of reads from raw data
    for i in range(len(sequences)):
        for j in range(i, len(sequences)):
            if i == j:
                local_reads = np.nansum(matrix.fetch(sequences[i])[:])
                reads[sequences[i]] += local_reads // 2 # divided by 2 because of the matrix symetry, simplified by ignoring the diagonal
            else:
                local_reads = np.nansum(matrix.fetch(sequences[i], sequences[j])[:])
                reads[sequences[i]] += local_reads
                reads[sequences[j]] += local_reads
    
    # Computing the average cov of the chromosomes
    chrom_coverages = [
        reads[chrom] / cool.chromsizes[chrom] for chrom in chromosomes
    ]
    average_cov = np.nanmedian(chrom_coverages)
    
    # computing contig coverage
    contig_coverage = reads[contig] / cool.chromsizes[contig]
    
    return contig_coverage/average_cov

In [6]:
plasmid = "AP023147.1"
library = "Entamoeba_histolytica"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome AP023109.1: 1.3767076991447766 copies.
Chromosome AP023110.1: 1.463853942454277 copies.
Chromosome AP023111.1: 1.1436256882749998 copies.
Chromosome AP023112.1: 1.546602404721493 copies.
Chromosome AP023113.1: 1.5669361140110278 copies.
Chromosome AP023114.1: 2.1231619180807533 copies.
Chromosome AP023115.1: 0.940728794570783 copies.
Chromosome AP023116.1: 1.2629898834102529 copies.
Chromosome AP023117.1: 1.5498292605498105 copies.
Chromosome AP023118.1: 1.4529017437485732 copies.
Chromosome AP023119.1: 1.7751325121167727 copies.
Chromosome AP023120.1: 1.262643840068002 copies.
Chromosome AP023121.1: 1.8330649431662795 copies.
Chromosome AP023122.1: 1.3748102878982782 copies.
Chromosome AP023123.1: 1.4198397970985335 copies.
Chromosome AP023124.1: 1.0539354175993527 copies.
Chromosome AP023125.1: 2.090967212419759 copies.
Chromosome AP023126.1: 1.2617314898758574 copies.
Chromosome AP023127.1: 0.5072687061679054 copies.
Chromosome AP023128.1: 1.1247731187494865 copies.
Chromosome AP023129.1: 1.0215782324985376 copies.
Chromosome AP023130.1: 0.6111195141013388 copies.
Chromosome AP023131.1: 0.5918143899738717 copies.
Chromosome AP023132.1: 0.3457286198492121 copies.
Chromosome AP023133.1: 0.25676484013711803 copies.
Chromosome AP023134.1: 0.3762980728891116 copies.
Chromosome AP023135.1: 0.2986869873235296 copies.
Chromosome AP023136.1: 0.22035054919605626 copies.
Chromosome AP023137.1: 0.18385663208441783 copies.
Chromosome AP023138.1: 0.4174367042375514 copies.
Chromosome AP023139.1: 0.5075802111570903 copies.
Chromosome AP023140.1: 0.995520552403144 copies.
Chromosome AP023141.1: 0.0 copies.
Chromosome AP023142.1: 0.0014750335814337988 copies.
Chromosome AP023143.1: 0.22115390210589414 copies.
Chromosome AP023144.1: 0.09275618877869236 copies.
Chromosome AP023145.1: 0.5587198757357428 copies.
Chromosome AP023146.1: 0.0 copies.
Contig AP023147.1: 276.98290776450864 copies.

# Fungi exploration

In [15]:
plasmid = "k59_3"
library = "Coprinellus_micaceus_contigs_1"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome ENA|OX596334|OX596334.1: 0.9615083125864468 copies.
Chromosome ENA|OX596335|OX596335.1: 1.1577722574715745 copies.
Chromosome ENA|OX596336|OX596336.1: 0.9469350866856648 copies.
Chromosome ENA|OX596337|OX596337.1: 0.9612939632008568 copies.
Chromosome ENA|OX596338|OX596338.1: 0.9683473704757427 copies.
Chromosome ENA|OX596339|OX596339.1: 1.0138006451665078 copies.
Chromosome ENA|OX596340|OX596340.1: 1.0139725439653553 copies.
Chromosome ENA|OX596341|OX596341.1: 0.9821008241444709 copies.
Chromosome ENA|OX596342|OX596342.1: 1.0190040514111094 copies.
Chromosome ENA|OX596343|OX596343.1: 1.0060596971666596 copies.
Chromosome ENA|OX596344|OX596344.1: 1.00378318266367 copies.
Chromosome ENA|OX596345|OX596345.1: 0.9607759006345623 copies.
Chromosome ENA|OX596346|OX596346.1: 1.0963041895476342 copies.
Chromosome ENA|OX596347|OX596347.1: 1.4481672377646149 copies.
Contig k59_3: 0.8334493075819394 copies.

In [14]:
plasmid = "ERR11512310_112"
library = "Chlorophyllum_brunneum_contigs_1"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome ENA|OY756139|OY756139.1: 0.9400302526365247 copies.
Chromosome ENA|OY756140|OY756140.1: 1.1198836292602483 copies.
Chromosome ENA|OY756141|OY756141.1: 1.0758116691699913 copies.
Chromosome ENA|OY756142|OY756142.1: 1.1036884711980763 copies.
Chromosome ENA|OY756143|OY756143.1: 0.8904642783270265 copies.
Chromosome ENA|OY756144|OY756144.1: 0.9951137388142611 copies.
Chromosome ENA|OY756145|OY756145.1: 1.066270343145962 copies.
Chromosome ENA|OY756146|OY756146.1: 0.9121069363804369 copies.
Chromosome ENA|OY756147|OY756147.1: 0.9468300392119282 copies.
Chromosome ENA|OY756148|OY756148.1: 0.9738383168714628 copies.
Chromosome ENA|OY756149|OY756149.1: 0.9774994738567752 copies.
Chromosome ENA|OY756150|OY756150.1: 0.976163393698366 copies.
Chromosome ENA|OY756151|OY756151.1: 1.0263919706901246 copies.
Chromosome ENA|OY756152|OY756152.1: 5.790278265012281 copies.
Contig ERR11512310_112: 0.4776715216267231 copies.

In [13]:
plasmid = "ERR12760796_54"
library = "Ganoderma_resinaceum_contigs_1"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome ENA|OZ026792|OZ026792.1: 0.9988249373353112 copies.
Chromosome ENA|OZ026793|OZ026793.1: 0.9590637016858824 copies.
Chromosome ENA|OZ026794|OZ026794.1: 0.9751534616019345 copies.
Chromosome ENA|OZ026795|OZ026795.1: 1.0647430091806251 copies.
Chromosome ENA|OZ026796|OZ026796.1: 1.0053629071321266 copies.
Chromosome ENA|OZ026797|OZ026797.1: 1.0126658544530867 copies.
Chromosome ENA|OZ026798|OZ026798.1: 1.0143413236652514 copies.
Chromosome ENA|OZ026799|OZ026799.1: 1.0164175193451295 copies.
Chromosome ENA|OZ026800|OZ026800.1: 0.9877192844726593 copies.
Chromosome ENA|OZ026801|OZ026801.1: 0.9505032760532552 copies.
Chromosome ENA|OZ026802|OZ026802.1: 0.9885647064349101 copies.
Chromosome ENA|OZ026803|OZ026803.1: 0.9517945819655276 copies.
Chromosome ENA|OZ026804|OZ026804.1: 1.0860017334738858 copies.
Chromosome ENA|OZ026805|OZ026805.1: 3.157577559063973 copies.
Contig ERR12760796_54: 0.8197108211148533 copies.

In [12]:
plasmid = "k141_28718"
library = "Tausonia_pullulans_contigs1"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome ENA|OX637620|OX637620.1: 1.0034335013606992 copies.
Chromosome ENA|OX637621|OX637621.1: 0.9857887606626428 copies.
Chromosome ENA|OX637622|OX637622.1: 1.0028548870634815 copies.
Chromosome ENA|OX637623|OX637623.1: 0.978272307040354 copies.
Chromosome ENA|OX637624|OX637624.1: 0.9893295435816883 copies.
Chromosome ENA|OX637625|OX637625.1: 0.8304205363083383 copies.
Chromosome ENA|OX637626|OX637626.1: 1.0188527978364417 copies.
Chromosome ENA|OX637627|OX637627.1: 0.9952189790062358 copies.
Chromosome ENA|OX637628|OX637628.1: 1.000806141617997 copies.
Chromosome ENA|OX637629|OX637629.1: 1.0275888142135523 copies.
Chromosome ENA|OX637630|OX637630.1: 1.0348917497702022 copies.
Chromosome ENA|OX637631|OX637631.1: 1.0080917024267333 copies.
Chromosome ENA|OX637632|OX637632.1: 1.0578836582924414 copies.
Chromosome ENA|OX637633|OX637633.1: 0.9830615890206681 copies.
Chromosome ENA|OX637634|OX637634.1: 0.9854972744631858 copies.
Chromosome ENA|OX637635|OX637635.1: 1.0358914095902803 copies.
Chromosome ENA|OX637636|OX637636.1: 0.9252111830295711 copies.
Chromosome ENA|OX637637|OX637637.1: 1.0194917239628642 copies.
Chromosome ENA|OX637638|OX637638.1: 0.9140300520429799 copies.
Chromosome ENA|OX637639|OX637639.1: 0.8298371922164177 copies.
Chromosome ENA|OX637640|OX637640.1: 1.7445409112767645 copies.
Contig k141_28718: 0.31487665826340083 copies.

# Saccharomyces cerevisiae Hi-Cs

In [7]:
# 2µ
plasmid = "J01347.1"
library = "S_cerevisiae_1"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
print(cool.chromnames)
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'Mito', 'J01347.1']
Chromosome I: 0.8512067164275825 copies.
Chromosome II: 1.0275577718745286 copies.
Chromosome III: 0.9303898333096541 copies.
Chromosome IV: 0.9677212417027828 copies.
Chromosome V: 1.0398632208013534 copies.
Chromosome VI: 0.9975008650631072 copies.
Chromosome VII: 1.0058659488509532 copies.
Chromosome VIII: 0.9676506624018117 copies.
Chromosome IX: 1.0274470813115502 copies.
Chromosome X: 1.027608930801098 copies.
Chromosome XI: 1.086696050866981 copies.
Chromosome XII: 0.8908155649791383 copies.
Chromosome XIII: 1.032155750378148 copies.
Chromosome XIV: 0.9859259461764756 copies.
Chromosome XV: 1.0124514879267998 copies.
Chromosome XVI: 0.9974647938283823 copies.
Chromosome Mito: 0.017730205016831754 copies.
Contig J01347.1: 45.723297071849586 copies.

In [8]:
# retrieved contigs
plasmid = "k39_18262"
library = "S_cerevisiae_contigs"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

plasmid = "k39_32520"
library = "S_cerevisiae_contigs"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome NC_001133.9: 0.8920483189973171 copies.
Chromosome NC_001134.8: 1.0341607395684171 copies.
Chromosome NC_001135.5: 0.9392993316242358 copies.
Chromosome NC_001136.10: 0.9662125990241435 copies.
Chromosome NC_001137.3: 1.0135420899778858 copies.
Chromosome NC_001138.5: 0.9999937585669119 copies.
Chromosome NC_001139.9: 1.0038569804393855 copies.
Chromosome NC_001140.6: 0.9850603103944421 copies.
Chromosome NC_001141.2: 1.0120988338646755 copies.
Chromosome NC_001142.9: 1.029345017551351 copies.
Chromosome NC_001143.9: 1.086256652914539 copies.
Chromosome NC_001144.5: 0.891202028944626 copies.
Chromosome NC_001145.3: 1.0355944617227222 copies.
Chromosome NC_001146.8: 0.984888026818081 copies.
Chromosome NC_001147.6: 1.0094485131842577 copies.
Chromosome NC_001148.4: 0.9989974550986915 copies.
Chromosome NC_001224.1: 0.09430254062403191 copies.
Contig k39_18262: 81.44125225825306 copies.
Chromosome NC_001133.9: 0.8920483189973171 copies.
Chromosome NC_001134.8: 1.0341607395684171 copies.
Chromosome NC_001135.5: 0.9392993316242358 copies.
Chromosome NC_001136.10: 0.9662125990241435 copies.
Chromosome NC_001137.3: 1.0135420899778858 copies.
Chromosome NC_001138.5: 0.9999937585669119 copies.
Chromosome NC_001139.9: 1.0038569804393855 copies.
Chromosome NC_001140.6: 0.9850603103944421 copies.
Chromosome NC_001141.2: 1.0120988338646755 copies.
Chromosome NC_001142.9: 1.029345017551351 copies.
Chromosome NC_001143.9: 1.086256652914539 copies.
Chromosome NC_001144.5: 0.891202028944626 copies.
Chromosome NC_001145.3: 1.0355944617227222 copies.
Chromosome NC_001146.8: 0.984888026818081 copies.
Chromosome NC_001147.6: 1.0094485131842577 copies.
Chromosome NC_001148.4: 0.9989974550986915 copies.
Chromosome NC_001224.1: 0.09430254062403191 copies.
Contig k39_32520: 71.36766095669805 copies.

In [17]:
# peculiar plasmids
plasmid = "pRS416"
library = "S_cerevisiae_pARS"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Plasmid {plasmid}: {nb_copies} copies.")

plasmid = "pRS416"
library = "S_cerevisiae_pRS416"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Plasmid {plasmid}: {nb_copies} copies.")

['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'Mito', 'pRS416']
Chromosome I: 0.9104205902516543 copies.
Chromosome II: 1.0261712740642555 copies.
Chromosome III: 0.97213841333407 copies.
Chromosome IV: 0.9483091457573831 copies.
Chromosome V: 1.0181040522066354 copies.
Chromosome VI: 1.0332975433531635 copies.
Chromosome VII: 0.9963218672600799 copies.
Chromosome VIII: 0.9777493325195068 copies.
Chromosome IX: 1.022685285020937 copies.
Chromosome X: 1.0230425373759324 copies.
Chromosome XI: 1.087061163304018 copies.
Chromosome XII: 0.8691028810925365 copies.
Chromosome XIII: 1.0294474017476876 copies.
Chromosome XIV: 0.9892919231872227 copies.
Chromosome XV: 1.0155992473869702 copies.
Chromosome XVI: 1.0090813275146262 copies.
Chromosome Mito: 0.11408434452893672 copies.
Plasmid pRS416: 4.823832714883854 copies.
Chromosome I: 0.8817078188549361 copies.
Chromosome II: 1.0240815869392694 copies.
Chromosome III: 0.9529608845000489 copies.
Chromosome IV: 0.9725139006776865 copies.
Chromosome V: 1.041354427509334 copies.
Chromosome VI: 1.0179504103970907 copies.
Chromosome VII: 1.0033457101160435 copies.
Chromosome VIII: 0.9687065817048894 copies.
Chromosome IX: 1.0176672828396383 copies.
Chromosome X: 1.0108712680400667 copies.
Chromosome XI: 1.0740474129419069 copies.
Chromosome XII: 0.9144262631940019 copies.
Chromosome XIII: 1.0420885777252091 copies.
Chromosome XIV: 0.9738139027883154 copies.
Chromosome XV: 1.0167190319908561 copies.
Chromosome XVI: 0.9992826546912118 copies.
Chromosome Mito: 0.4928385915659107 copies.
Plasmid pRS416: 3.1259200596278105 copies.

## D. discoideum

In [2]:
# retrieved contigs
plasmid = "k39_4350"
library = "D_discoideum_contigs"
binning = 15000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or chrom[:3] == "NC_" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    nb_copies = compute_number_of_copies(cool, chrom_tmp, chromosomes[i])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies.")

nb_copies = compute_number_of_copies(cool, chromosomes, plasmid)
print(f"Contig {plasmid}: {nb_copies} copies.")

Chromosome NC_007087.3: 0.9241980976449522 copies.
Chromosome NC_007088.5: 0.7687409232262992 copies.
Chromosome NC_007089.4: 0.9906529196054044 copies.
Chromosome NC_007090.3: 1.0896889236427116 copies.
Chromosome NC_007091.3: 1.0474098210775447 copies.
Chromosome NC_007092.3: 0.9624407485488321 copies.
Chromosome NC_000895.1: 21.90681653969333 copies.
Contig k39_4350: 82.47979427633919 copies.

## Looking for high copy number in contigs

In [69]:
def coverage(matrix, sequence, chromosomes):
    """Return the number of reads"""
    sequences = chromosomes
    nb_reads = 0
    for i in range(len(sequences)):
        local_reads = np.nansum(matrix.fetch(sequence)[:]) if sequences[i] == sequence else np.nansum(matrix.fetch(sequences[i], sequence)[:])
        nb_reads += local_reads if sequences[i] == sequence else local_reads // 2 # divided by 2 because of the matrix symetry, simplified by ignoring the diagonal
    return nb_reads
    
def compute_all_contigs_copy_number(cool, chromosomes, ploidy = 1):
    """Estimates the number of copies of all the contigs in the genome from Hi-C data (cool file). 
    The following formula is applied:
        # copies = Cov(contig)/Median(Cov(chromosome))
    with Cov(x) = Reads(x)/Ploidy*Size(x) for any sequence x, 
    with the Ploidy = 2 for Diploid genomes, and 1 for Haploid genomes.
    """
    matrix = cool.matrix(balance = False)
    # computing each chomosome copy number and median
    chromosomes_copy = [
        coverage(matrix, chrom, chromosomes)/(ploidy * cool.chromsizes[chrom])
        for chrom in chromosomes
    ]
    av_chrom_copy = np.nanmedian(chromosomes_copy)
                                
    # computing each contig coverage
    contigs_cov = {}
    contigs_copy = {}
    i = 0
    for contig in cool.chromnames:
        if contig in chromosomes:
            continue
        contigs_cov[contig] = coverage(matrix, contig, chromosomes)
        if contigs_cov[contig] == 0:
            continue
        i += 1
        if i % 100 == 0:
            print(f"{i} sequences processed.")
        contigs_copy[contig] = (contigs_cov[contig] / (ploidy * cool.chromsizes[contig])) / av_chrom_copy
    contigs_list = contigs_copy.keys()
    copy_df = pd.DataFrame([
        list(contigs_list),
        [cool.chromsizes[contig] for contig in contigs_list],
        [contigs_cov[contig] for contig in contigs_list], 
        [contigs_copy[contig] for contig in contigs_list]
    ]).T
    copy_df.columns = ["Contig", "Size", "Coverage", "Estimated # copy"]
    return copy_df

In [3]:
library = "Tausonia_pullulans_contigs1"
binning = 100000
cool_file = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/mcools/{library}.mcool"
plot_outpath = f"/media/sardine/data_2/Eukaroytic_plasmids_manual_research/contact_plots/{library}"
if not os.path.exists(plot_outpath):
    os.mkdir(plot_outpath)
cool = cooler.Cooler(f"{cool_file}::resolutions/{binning}")
matrix = cool.matrix(balance = False)
chromosomes = np.array([ chrom for chrom in list(cool.chromsizes.keys()) if chrom[:3] == "ENA" or (chrom[:3] != "ERR" and chrom[0] != "k" and chrom[:3] != "tig" and chrom != plasmid)])

for i in range(len(chromosomes)):
    chrom_tmp = chromosomes[1:] if i == 0 else np.concatenate([chromosomes[:i-1], chromosomes[i + 1:]]) if i < len(chromosomes) else chromsomes[:-1]
    cov = coverage(matrix, chromosomes[i], chrom_tmp)
    nb_copies = cov/(2 * cool.chromsizes[chromosomes[i]])
    print(f"Chromosome {chromosomes[i]}: {nb_copies} copies (coverage = {cov} reads).")

all_contigs_copy = compute_all_contigs_copy_number(cool, chromosomes, ploidy = 2)

NameError: name 'coverage' is not defined

In [71]:
min_copy = 0.01
all_contigs_copy[all_contigs_copy["Estimated # copy"] >= min_copy]

        Contig  Size Coverage Estimated # copy
11   k141_8466  8189     1262         0.024376
50  k141_28718  6972     9097          0.20638

In [72]:
min_cov = 1000
all_contigs_copy[all_contigs_copy["Coverage"] >= min_cov]

        Contig  Size Coverage Estimated # copy
11   k141_8466  8189     1262         0.024376
50  k141_28718  6972     9097          0.20638